###############################################################################
# Services for development only
# IMPORTANT!!! Data is wiped on provision
###############################################################################

services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: cms-mongodb
    network_mode: host
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - MONGODB_INITDB_DATABASE=localhost
    volumes:
      - ./database/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
